name: Test FEEL expressions

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  drools-matrix:
    strategy:
      matrix:
        drools_version: [9.44.0.Final, 999-SNAPSHOT]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: $-jbang-$
          restore-keys: |
            $-jbang-
      - name: jbang
        uses: jbangdev/jbang-action@v0.116.0
        with:
          script: test.java
          jbangargs: -Ddrools.version=${{ matrix.drools_version }}
